language: generic

services:
  - docker

before_install:
  - docker pull flycheck/emacs-cask:26.2

script:
- docker run -it --rm flycheck/emacs-cask:26.2 emacs --version
- docker run -v ${TRAVIS_BUILD_DIR}:/root/.emacs.d -it --rm flycheck/emacs-cask:26.2 bash -c "cd /root/.emacs.d && cask && emacs --batch --load /root/.emacs.d/init.el  --execute '(print \"great success\")'"
